# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
     app.doctrine.hash_password_listener:
         class: AppBundle\Doctrine\HashDataListener
         autowire: true
         arguments: ['@security.encoder_factory']
         tags:
             - { name: doctrine.event_subscriber }

    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
